- package.json
- src/index.ts
- tests/tsconfig.json
- tsconfig.json
It is better to test code on release env, I think. As bonus, no need to use different syntax for `slash` import, es6 everywhere )).
> Import in tests transformer from lib

- package.json
- src/index.ts
- tests/__fixtures/with-path/core/index.ts
- tests/__fixtures/with-path/secondary/hello.ts
- tests/__fixtures/with-path/tsconfig.json
- tests/__fixtures/with-path/utils/index.ts
- tests/__fixtures/without-path/dir2/other.ts
- tests/index.ts
- tests/tsconfig.json
- Allow more than one path routing (fixes #60)
- Remove implicit extensions from output (fixes #24)
- Properly implemented isTypeOnly (fixes #48)
- Corrected errors in tests due to TS changing logic for type only star exports
- Bonus: Made package zero-dependency
> fix: multiple issue fixes

- package.json
- src/index.ts
- tests/__fixtures/specific/src/type-elision/a.ts
- tests/__fixtures/specific/src/type-elision/index.ts
- tests/transformer.test.ts
Fixes #72 
TypeScript type elision breaks when we transform an `ImportDeclaration`, `ExportDeclaration`, or the child property `moduleSpecifier` on either of the former. (see: microsoft/TypeScript#40603). This resulted in type exports being output in resulting js output instead of the normal elision behaviour.
To work around this, we used `ts.updateNode` in TS <4. In version 4+, however, this method was removed.
Our first attempt at a new workaround was successful at restoring elision, however, it would break in instances where specific node-based information such as diagnostics were still referenced elsewhere. This is because we circumvented the API to directly replace the `moduleSpecifier` property with a newly created `StringLiteral`.
We are now using the new `updateNode` method of the …
> Fix various issues with TS workaround

- src/utils/resolve-path-update-node.ts
My goal was to import preact like this:
```typescript
import { render, h } from 'preact';
```
But have my JS code like this:
```javascript
import { render, h } from "https://cdnjs.cloudflare.com/ajax/libs/preact/10.5.7/preact.module.min.js";
```
But instead I was getting
```javascript
import { render, h } from 'preact';
```
So I looked at the code here and made a few changes that solved my problem, I am not sure if this breaks anything else, havent tested it, but it worked to solve my problem, so here it is.
Documentation on the feature/option:
Option: overwriteNodeModules
```json
{
"transform": "typescript-transform-paths",
"overwriteNodeModules" : true
}
```
If you wish to replace an import for a package that exists on node_modules you can set the option "overwriteNodeModules".
This can …
> Goal: add option to overwrite existing modules

- README.md
The link URL has a double quote in the end, preventing it from redirecting properly to the article author GitHub profile
> docs: fix broken article author link

- src/transformer.ts
- src/types.ts
- src/utils/ts-helpers.ts
Development versions of TS 4.4 contains a breaking change in the public `matchPatternOrExact` utility function. Specifically, changes were made to add caching to the paths pattern parsing to speed things up.
Relevant commit: https://github.com/microsoft/TypeScript/commit/3ffa245f07c4472ed3015fcb59ea0d2d73432102
Fixing this now due to multiple users using dev builds with issues. More changes may be necessary if logic changes in official release.
> fix: Accommodate TS 4.4 paths pattern caching (fixes #114)

- src/utils/ts-helpers.ts
Overwriting `Program.compilerOptions` with merged form caused issues in edge cases
> fix: More edge cases in ts-node (fixes #163)

- .github/workflows/publish.yml
- src/utils/general-utils.ts
- src/utils/resolve-module-name.ts
- test/prepare.js
- test/tests/transformer/specific.test.ts
fixes so all paths dont get rewritten to `../../../../../../../users/...` on osx 
fixes #167
> I just edited the project using github editor so it wouldn't have styles and such - but this does fix the issue on my project and follows with what the solution was on #167 - figure it'd be ideal to just put this forward for you to merge if all looks well!
> fix: fix osx root path issues

- src/utils/resolve-path-update-node.ts
**TL;DR**
Allow running tsc in debug mode when using `typescript-transform-paths` plugin.
**Full Explanation:**
Sometimes it makes sense to run tsc in debug mode. For example in my case, we run tsc + start server in watch mode e.g. `tsc-watch --compiler ttypescript/bin/tsc --onSuccess 'npm start'`. 
And if we run this in a debug session like on VSCode's debug terminal, it means we run both tsc and our sever in debug mode.
The problem is that when typescript throws errors on internal assertions it's also putting a "debugger;" statement right before it throws an error.
There's a block of code in this package ([typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths)) that wraps such TS errors in a try/catch. That causes our servers to get stuck (repeatedly) on a …
> getStatementTags | Avoid unnecessary TS debugger statement invocations

- .github/workflows/main.yml
push events on GitHub Action were already running on the pull requests.
Before
Now
> ci: remove duplicated checks on gh

- .github/workflows/publish.yml
- .prettierignore
- README.md
- jest.config.ts
- nx-transformer.js
- package.json
- register.js
- src/utils/elide-import-export.ts
- test/prepare.js
- test/projects/extras/tsconfig.json
- test/projects/general/tsconfig.json
- test/projects/nx/packages/library1/project.json
- test/projects/nx/packages/library2/project.json
- test/projects/project-ref/a/tsconfig.json
- test/projects/project-ref/b/tsconfig.json
- test/projects/project-ref/tsconfig.base.json
- test/projects/specific/tsconfig.json
- test/tests/transformer/specific.test.ts
- test/tsconfig.json
- tsconfig.base.json
- tsconfig.json
- types/index.d.ts
see #211 
Ran `yarn prettier --write .`
> chore: format code with prettier

- .github/workflows/main.yml
- removed actions/cache in favor of setup/node own caching
- used corepack to select yarn version
> ci: update test workflows to use setup/node action cache and corepack

- .github/workflows/main.yml
- .gitignore
- package.json
- test/config.ts
- test/jest.config.ts
- test/package.json
- test/projects/extras/package.json
- test/projects/general/tsconfig.json
- test/projects/nx/package.json
- test/projects/project-ref/package.json
- test/projects/project-ref/tsconfig.base.json
- test/tests/extras.test.ts
- test/tests/nx.test.ts
- test/tests/register.test.ts
- test/tests/transformer/specific.test.ts
- test/utils/helpers.ts
- test/yarn.lock
- types/index.d.ts
- types/register.d.ts
- yarn.lock
Use the generated tarball from `yarn pack` when running the tests. This way the dependencies resolution is more accurate to the user environment and we avoid some "hacks" using link: and file:
Replaced npx calls with yarn
We might not need this workaround in yarn berry https://github.com/LeDDGroup/typescript-transform-paths/pull/199
> refact: use yarn pack to generate package for testing

- .github/workflows/main.yml
- package.json
- test/package.json
- test/yarn.lock
- yarn.lock
Reverts the installation workaround introduced in https://github.com/LeDDGroup/typescript-transform-paths/pull/216.
Since we changed the `ts-node` dev dependency to `@types/ts-node`, now it's not resolved by node's `require`
> chore: don't install ts-node on development, just the types

- .github/workflows/publish.yml
- README.md
- package.json
- yarn.lock
[standard-version](https://www.npmjs.com/package/standard-version) has been deprecated for a while.
[changelogen](https://github.com/unjs/changelogen) seems like a promising replacement from the unjs ecosystem.
Tested this workflow in some of my other packages and LGTM
> chore: replace standard-version with changelogen

- .github/workflows/publish.yml
Closes #228 
Example of publishing with --provenance
([gh run](https://github.com/LeDDGroup/typescript-transform-paths/actions/runs/10295350654/job/28494897900))
> ci: generate provenance on npm publish

- README.md
All Contributors hasn't been used in a while, the badge is outdated
> docs: remove all contributors badge

- eslint.config.mjs
- src/harmony/versions/four-seven.ts
- src/harmony/versions/index.ts
- src/harmony/versions/three-eight.ts
- src/register.ts
Removing typescript only namespaces in favor of using modules per typescript recommendation. This should produce more compliant code and output more readable javascript
[From typescript](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#using-modules)
> It is also worth noting that, for Node.js applications, modules are the default and we recommended modules over namespaces in modern code.
> Starting with ECMAScript 2015, modules are native part of the language, and should be supported by all compliant engine implementations. Thus, for new projects modules would be the recommended code organization mechanism.
See [the diff](https://github.com/LeDDGroup/typescript-transform-paths/pull/236/files?diff=unified&w=1) without whitespace changes
> refact: remove namespaces in favor of modules

- eslint.config.mjs
- src/register.ts
- src/utils/ts-helpers.ts
- test/config.ts
- test/tests/extras.test.ts
- test/tests/register.test.ts
- test/utils/helpers.ts
- test/utils/index.ts
- test/utils/module-not-found-error.ts
Removed `require`s in favor of `import`. Kept it in a couple of places where using import was not possible.
Also replaced the `require('fake-module')` in favor of simulating a nodejs MODULE_NOT_FOUND error for testing
> refact: fix no-require-imports eslint warning

- package.json
- test/tests/nx.test.ts
- test/tests/register.test.ts
> feat: add package.json exports

- package.json
- test/yarn.lock
- yarn.lock
https://github.com/LeDDGroup/typescript-transform-paths/issues/271
downgrade the minimatch dependency from 10.0.1 to 9.0.5 to remove a node 20 dependency.
> chore(deps): downgrade minimatch from 10.0.1 to 9.0.5

- src/transformer.ts
- test/config.ts
- test/package.json
- test/prepare.mjs
- test/tests/extras.test.ts
- test/yarn.lock
This PR restores compatibility with TypeScript 5.6. It also updates the test suite to be more resilient and explicitly tests against TypeScript 5.5 and 5.6.
I was surprised that TypeScript would break this without releasing a major version. However, if you look at the `getOriginalSourceFile` method we were using, it was marked as `@internal` in the JSDoc: https://github.com/microsoft/TypeScript/blob/c8a7d589e647e19c94150d9892909f3aa93e48eb/src/compiler/utilities.ts#L5416-L5419
Because it was marked as internal, they probably reserved the right to remove this method without a breaking version bump. The other PR to fix this issue (#270) suggested using `getSourceFileOfNode`, but that's also marked as `@internal`: https://github.com/microsoft/TypeScript/blob/11b2930fa2c9f73b0ffb725a9715b8d3c4 …
> fix: restore typescript 5.6 compatibility

- src/utils/get-relative-path.ts
- test/tests/get-match-portion.test.ts
Today typescript-transform-paths changes the case of import statements on a case-insensitive file system. I have a file `Foo` and an import `from "./Foo"`, yet after the transformation with typescript-transform-paths, the import looks like `"./foo"`. Even if that import would work on a case-insensitive file system, it seems clearly undesirable.
Note that #187 does _not_ fix the issue above.
> fix(paths): respect desired path on case-insensitive file systems
